### ISSUE TITLE
Answer for your TODO

### ISSUE THREAD

**Issue by TheKevJames** [stevenkaras/bashfiles#1]
With regards to [this TODO](https://github.com/stevenkaras/bashfiles/blob/master/bin/bash_historian#L9): if you replace

```
history | cut -c30-
```
with
```
history -n | awk '{$1=$2=""; sub(/^[ \t]+/, ""); print $0}'
```
you should get the behaviour you're looking for.

**Comment by stevenkaras** [comment]
So that didn't work the way I expected it to at all. The purpose of the cut is to remove the timestamp at the start of the line, which is a bit of a mistake. It'd be better to invoke history with HISTTIMEFORMAT set to an empty string, and remove the first field, then trim the remaining space.

I'm on the fence if I want it to actually extract the command invocation at all, since that's nontrivial (parse out environment variables, hope it isn't a control structure, etc.). But I'll probably have to do that anyways for other parts of this utility, so it's probably inevitable, but not coming soon.

**Comment by TheKevJames** [comment]
Hmm I must have missed the point of your TODO; as far as I understand you, that is what my command does!

```
» history | tail -n2
 3579  2018-04-27 14:50  history | cut -c24- | tail -n2
 3580  2018-04-27 14:50  history | cut -c26- | tail -n2
» history | cut -c26- | tail -n2
history | cut -c26- | tail -n2
history | tail -n2
» history -n | awk '{$1=$2=""; sub(/^[ \t]+/, ""); print $0}' | tail -n2
history | tail -n2
history | cut -c26- | tail -n2
```

`history -n` removes the counter, and the `awk` command strips the datetime and the remaining space.

Then you get
```
» history -n | awk '{$1=$2=""; sub(/^[ \t]+/, ""); print $0}' | grep -e "ls" | sort | uniq -c | sort -n -r | head
   3 ls -la .config/sublime-text-3/Packages/User
   2 ls | wc -l
   2 ls -la ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
   2 ls -la ~/Library/Application\ Support/Franz/recipes
   2 ls -la ~/.config/sublime-text-3/Packages/User
   2 ls -la
   1 sudp ls -la /etc/NetworkManager/system-connections/
   1 sudo ls -la /etc/NetworkManager/system-connections/
   1 sudo find . -type f -name '*.DS_Store' -ls -delete; sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl
   1 sudo find . -type f -name '*.DS_Store' -ls -delete; sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl*.asl
```

**Comment by stevenkaras** [comment]
`history -n` loads any unsynced history entries, at least for the versions of bash I work with. What shell and version are you working with?

The point of the TODO was to clean up the field manipulations, so it doesn't do the relatively stupid fixed field width cut (I routinely work on machines with histories of 10s of commands, but my work laptop has over 100000 in its history). The right aligned, flexible width number field is what I was hoping to handle more elegantly.

**Comment by TheKevJames** [comment]
Huh, for some reason I thought `history -n` was "`history` without the command count. Failure of reasoning on my part!

Well, in that case, the command would be
```
history | awk '{$1=$2=$3=""; sub(/^[ \t]+/, ""); print $0}'
```

Note the removed `-n` and added `$3=`

**Comment by stevenkaras** [comment]
I'd rather keep it simple:

```bash
HISTTIMEFORMAT="" history | awk '{$1=""; sub(/^[ \t]+/, ""; print $0}'
```

Which is a lot cleaner, and avoids any potential locale issues. Ideally, it's possible to tell the `history` builtin to only emit commands without entry numbers.

**Comment by TheKevJames** [comment]
TIL about the `HISTTIMEFORMAT` variable, cool!
